cookbook/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#welcome'
  resources :recipes
end

cookbook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cookbook/app/models/recipe.rb
class Recipe < ApplicationRecord
   validates :title, :recipe_type, :cuisine, :difficulty, :cook_time, :ingredients, :cook_method, presence: true
   
   def cook_time_min
    "#{cook_time} minutos"
    end    

end

cookbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cookbook/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
        @featured_recipes = Recipe.where(featured: true)
        @other_recipes = Recipe.where(featured: false)
    end
end    

cookbook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def show
        @recipe = Recipe.find(params[:id])
    end

    def new
        @recipe = Recipe.new
    end   
    
    def create
        # Receber uma receita
        recipe_params = params.require(:recipe).permit(:title,:recipe_type,:cuisine,:difficulty,
                                                      :cook_time,:ingredients,:cook_method)
        @recipe = Recipe.new(recipe_params)

        if @recipe.save
            redirect_to recipe_path(@recipe.id) 
        else
            # Redirecionar para a receia recem criada
            render 'new'
        end    
    end   
    
    def edit
        @receita = Recipe.find(params[:id])
    end 
    
    def update
        # Carreguei a receita pelo ID
        @receita = Recipe.find(params[:id])
        # Recebe a nova informação e atualiza
        recipe_params = params.require(:recipe).permit(:title,:recipe_type,:cuisine,:difficulty,
        :cook_time,:ingredients,:cook_method)

        if @receita.update(recipe_params)
            redirect_to recipe_path(@receita)
        else
            # Redirecionar para a receia recem criada
            render 'edit'
        end    
        
        #leva o usuario para o show receita
        
    end    

end    

cookbook/app/helpers/application_helper.rb
module ApplicationHelper
end

cookbook/app/views/home/welcome.html.erb
<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online'</p>
<%= link_to 'Home',  root_path, class: 'nav-link' %>
<%= link_to 'Enviar uma receita', new_recipe_path, class: 'nav-link'%>
<h3>Receitas destaque</h3>
<div id="recipes-featured" >
<% @featured_recipes.each do |recipe| %>
    <%= image_tag 'star.png'%>
    <h1><%= link_to recipe.title, recipe%>/h1>
    <ul>
        <li><%= recipe.recipe_type %></li>
        <li><%= recipe.cuisine %></li>
        <li><%= recipe.difficulty %></li>
        <li><%= recipe.cook_time_min %></li>
    </ul>
<% end %>
</div>
<h3>Outras Receitas</h3>
<div id="other-recipes" >
<% @other_recipes.each do |recipe| %>
    <h1><%= link_to recipe.title, recipe%>/h1>
    <ul>
        <li><%= recipe.recipe_type %></li>
        <li><%= recipe.cuisine %></li>
        <li><%= recipe.difficulty %></li>
        <li><%= recipe.cook_time_min %></li>
    </ul>
<% end %>
</div>

cookbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cookbook/app/views/recipes/edit.html.erb
<h1>Editar Receita</h1>

<%if @receita.errors.any? %>
<p>Você deve informar todos os dados da receita</p>
<%end%>

<%= form_for @receita do |f|%>
    <div> 
    <%= f.label :title, 'Título'%>
    <%= f.text_field :title%>
   </div>
   <div> 
    <%= f.label :recipe_type, 'Tipo da Receita'%>
    <%= f.text_field :recipe_type%>
   </div>
   <div> 
    <%= f.label :cuisine, 'Cozinha'%>
    <%= f.text_field :cuisine%>
   </div>   
   <div> 
    <%= f.label :difficulty, 'Dificuldade'%>
    <%= f.text_field :difficulty%>
   </div>    
   <div> 
   <%= f.label :cook_time, 'Tempo de Preparo'%>
   <%= f.number_field :cook_time%>
  </div>   
   <div> 
   <%= f.label :ingredients, 'Ingredientes'%>
   <%= f.text_field :ingredients%>
   </div> 
   <div> 
   <%= f.label :cook_method, 'Como Preparar'%>
   <%= f.text_field :cook_method%>
   </div> 

   <%= f.submit 'Enviar'%>
<%end%>    

cookbook/app/views/recipes/new.html.erb
<h1>Cadastrar Nova Receita</h1>

<%if @recipe.errors.any? %>
<p>Você deve informar todos os dados da receita</p>
<%end%>

<%= form_for(@recipe) do |f|%>
   <div> 
    <%= f.label :title, 'Título'%>
    <%= f.text_field :title%>
   </div>
   <div> 
    <%= f.label :recipe_type, 'Tipo da Receita'%>
    <%= f.text_field :recipe_type%>
   </div>
   <div> 
    <%= f.label :cuisine, 'Cozinha'%>
    <%= f.text_field :cuisine%>
   </div>   
   
   <div> 
    <%= f.label :difficulty, 'Dificuldade'%>
    <%= f.text_field :difficulty%>
   </div>    
   <div> 
   <%= f.label :cook_time, 'Tempo de Preparo'%>
   <%= f.number_field :cook_time%>
  </div>   
 
   <div> 
   <%= f.label :ingredients, 'Ingredientes'%>
   <%= f.text_field :ingredients%>
   </div> 
   <div> 
   <%= f.label :cook_method, 'Como Preparar'%>
   <%= f.text_field :cook_method%>
   </div> 

   <%= f.submit 'Enviar'%>
<%end%>    

cookbook/app/views/recipes/show.html.erb
<h1><%= @recipe.title%></h1>
<h3>Detalhes</h3><br>
<p><%= @recipe.recipe_type %></p>
<p><%= @recipe.cuisine %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time_min %></p>
<h3>Ingredientes</h3>
<p><%=@recipe.ingredients%></p>
<h3>Como Preparar</h3>
<p><%=@recipe.cook_method%></p>
<%= link_to "Editar", edit_recipe_path(id: @recipe.id), class: "btn btn-primary" %>
<%= link_to "Voltar", root_path, class: "btn btn-secondary" %>